// var fakeList = [
//     {
//         name: 'Olatukoop batzarra',
//         data: '2019/11/17',
//         type: 'enterprise-event',
//         enterprise: 'skura',
//         enterpriseType: 'tecnology',
//         eventDate: '2019-11-17',
//         eventInitHour: '12:00',
//         eventFinishHour: '13:00',
//         like: 144,
//         menbers: 34,
//         direction: 'Torrekua 2 - 2.solairua - Orereta',
//         region: {
//             latitude: 43.3220449,
//             longitude: -1.9001347,
//             latitudeDelta: 0.0922,
//             longitudeDelta: -1.8936556,
//         },
//         marker: require('../../resources/png/marker/marker-01.png'),
//         image: 'https://halabedi.eus/wp-content/uploads/2018/01/jendea.jpg',
//         description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'

//     },
//     {
//         name: 'Olatukopp festa 2019',
//         data: '2019-11-17',
//         type: 'news',
//         like: 144,
//         menbers: 34,
//         direction: 'torrekua 2 2.solairua',
//         region: {
//             latitude: 43.322928,
//             longitude: -1.9006703,
//             latitudeDelta: 0.0922,
//             longitudeDelta: -1.8936556,
//         },
//         marker: require('../../resources/png/marker/marker-02.png'),
//         image: 'https://urolakosta.hitza.eus/site/files/2018/06/DfP410FW0AAhVL2_content.jpg',
//         description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'

//     },
//     {
//         name: 'Lan duinaren aldeko ekimena',
//         data: '2019-11-17',
//         type: 'event',
//         enterprise: 'skura',
//         enterpriseType: 'tecnology',
//         eventDate: '2019/11/17',
//         eventInitHour: '12:00',
//         eventFinishHour: '13:00',
//         like: 144,
//         menbers: 34,
//         direction: 'torrekua 2 2.solairua',
//         region: {
//             latitude: 43.3087261,
//             longitude: -1.8936556,
//             latitudeDelta: 0.0922,
//             longitudeDelta: -1.8936556,
//         },
//         marker: require('../../resources/png/marker/marker-03.png'),
//         image: 'https://www.eldiario.es/clm/Reas_EDIIMA20180427_0600_19.jpg',
//         description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'

//     },
//     {
//         name: 'Reasek antolatutako hitzaldia',
//         data: '2019-11-17',
//         type: 'enterprise-news',
//         enterprise: 'skura',
//         enterpriseType: 'tecnology',
//         like: 144,
//         menbers: 34,
//         direction: 'torrekua 2 2.solairua',
//         region: {
//             latitude: 43.3190809,
//             longitude: -1.923591,
//             latitudeDelta: 0.0922,
//             longitudeDelta: -1.8936556,
//         },
//         marker: require('../../resources/png/marker/marker-04.png'),
//         image: 'https://www.economiasolidaria.org/sites/default/files/inline-images/Panel-puestoREAS.jpg',
//         description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'

//     },
//     {
//         name: 'Merkatu soziala 2019',
//         data: '2019-11-17',
//         type: 'help',
//         enterprise: 'skura',
//         enterpriseType: 'tecnology',
//         like: 144,
//         menbers: 34,
//         direction: 'torrekua 2 2.solairua',
//         region: {
//             latitude: 43.3184131,
//             longitude: -1.9376942,
//             latitudeDelta: 0.0922,
//             longitudeDelta: -1.8936556,
//         },
//         marker: require('../../resources/png/marker/marker-05.png'),
//         image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYszXqdvTqUTB83pyCwEc9-07LoEhmoVgZkJ5AzDMIicLCyKcP',
//         description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'

//     },
//     {
//         name: 'Greba feminista',
//         data: '2019-11-17',
//         type: 'enterprise-news',
//         enterprise: 'skura',
//         enterpriseType: 'tecnology',
//         like: 144,
//         menbers: 34,
//         direction: 'torrekua 2 2.solairua',
//         region: {
//             latitude: 43.3091762,
//             longitude: -1.9106498,
//             latitudeDelta: 0.0922,
//             longitudeDelta: -1.8936556,
//         },
//         marker: require('../../resources/png/marker/marker-06.png'),
//         image: 'https://madrid.mercadosocial.net/land/wp-content/uploads/8M_ReasMes.jpg',
//         description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'

//     }, {
//         name: 'Hezkuntza ardatz',
//         data: '2019/11/17',
//         type: 'enterprise-event',
//         enterprise: 'skura',
//         enterpriseType: 'tecnology',
//         eventDate: '2019-11-17',
//         eventInitHour: '12:00',
//         eventFinishHour: '13:00',
//         like: 144,
//         menbers: 34,
//         direction: 'torrekua 2 2.solairua',
//         region: {
//             latitude: 43.3091863,
//             longitude: -1.930838,
//             latitudeDelta: 0.0922,
//             longitudeDelta: -1.8936556,
//         },
//         marker: require('../../resources/png/marker/marker-07.png'),
//         image: 'https://www.reasred.org/sites/default/files/styles/large/public/reaslibrary/images/la%20ess%20en%20en%20contexto%20educativo.png?itok=BlVxLi2e',
//         description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'

//     },
//     {
//         name: 'Elikadura burujabetza',
//         data: '2019-11-17',
//         type: 'event',
//         enterprise: 'skura',
//         enterpriseType: 'tecnology',
//         eventDate: '2019/11/17',
//         eventInitHour: '12:00',
//         eventFinishHour: '13:00',
//         like: 144,
//         menbers: 34,
//         direction: 'torrekua 2 2.solairua',
//         region: {
//             latitude: 43.3124791,
//             longitude: -1.9297594,
//             latitudeDelta: 0.0922,
//             longitudeDelta: -1.8936556,
//         },
//         marker: require('../../resources/png/marker/marker-08.png'),
//         image: 'https://somalimentacio.com/wp-content/uploads/2019/04/pegatinasREAS1-min-300x300.png',
//         description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'

//     },
//     {
//         name: 'Reas2019 kanpaña',
//         data: '2019-11-17',
//         type: 'enterprise-news',
//         enterprise: 'skura',
//         enterpriseType: 'tecnology',
//         like: 144,
//         menbers: 34,
//         direction: 'torrekua 2 2.solairua',
//         region: {
//             latitude: 43.3087967,
//             longitude: -1.8936556,
//             latitudeDelta: 0.0922,
//             longitudeDelta: -1.8936556,
//         },
//         marker: require('../../resources/png/marker/marker-09.png'),
//         image: 'https://reliwebzgz.files.wordpress.com/2013/04/graf1.jpg?w=299&h=300',
//         description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'

//     }
// ]
export const  fakeList_2 = [
    {
        name: 'MUGARIK GABEKO EKONOMISTEN UDAKO IKASTAROA',
        data: '2019/11/17',
        type: 'enterprise-event',
        enterprise: 'Reas',
        enterpriseType: 'tecnology',
        eventDate: '2019-11-17',
        eventInitHour: '12:00',
        eventFinishHour: '13:00',
        like: 144,
        menbers: 34,
        direction: 'Villaverde, San Fermín Alberguen',
        region: {
            latitude: 43.3220449,
            longitude: -1.9001347,
            latitudeDelta: 0.0922,
            longitudeDelta: -1.8936556,
        },
        image: 'https://ecosfron.org/wp-content/uploads/EdVWEB.png',
        description: 'Uztailaren 15etik 17ra, Villaverde, San Fermín Alberguen, Madrilen.Uztailean, udako eskola datorkigu berriz ere, non akademikotik zein gizarte mugimenduetatik datorren pertsonak izango ditugun gure artean, ekonomia ulertu eta egiteko moduetaz hausnartzeko.\n\nEdizio honetan desberdintasunaren arazoa eta egungo sistema ekonomikoaren funtzionamenduarekin duen lotura aztertuko dugu.',
        info:'https://ecosfron.org/escuela-de-verano/',

    },
    {
        name: 'Baserriak energia autonomiarako bide berrien bila',
        data: '2019-11-17',
        type: 'news',
        enterprise: 'skura',
        enterpriseType: 'tecnology',
        like: 144,
        menbers: 34,
        direction: 'torrekua 2 2.solairua',
        region: {
            latitude: 43.3087967,
            longitude: -1.8936556,
            latitudeDelta: 0.0922,
            longitudeDelta: -1.8936556,
        },
        image: 'https://www.argia.eus/astekaria/docs/2644/argazkiak/41.jpg',
        description: 'Ekoizpen ekologikoan ziharduten zenbait abeltzainek egin zuten lehen proposamena: zer egin zezaketen baserritarrek beren autonomia energetikoan sakontzeko?\nMirene Begiristain EHUko ikerlariaren hitzak dira.\n\nBaserritarren proposamena hartu eta Energia Sortzen proiektuan lanean aritu dira Gipuzkoako hainbat eskualdetako bost abeltzain proiektu, Biolur, Lurgintza eta Goiener elkartea. Lehen helburua?\n Gipuzkoako bost baserriren jarduna oinarri hartuta diagnostikoa osatzea: energia kontsumoa murrizteko eta baliabide propioekin energia sortzeko eman daitezkeen pausoak aztertu dituzte ENEEK (Euskadiko Nekazaritza eta Elikadura Ekologikoaren Kontseilua) eta, Gipuzkoako Aldundiaren bitartez, Landaola Federazioaren erakundeen finantzaketarekin.',
        info:'https://www.argia.eus/argia-astekaria/2644/baserriak-energia-autonomiarako-bide-berrien-bila '

    },
    {
        name: 'Curso Internacional - Alternativas en transición hacia una economía popular',
        data: '2019-11-17',
        type: 'news',
        enterprise: 'skura',
        enterpriseType: 'tecnology',
        like: 144,
        menbers: 34,
        direction: 'torrekua 2 2.solairua',
        region: {
            latitude: 43.3087967,
            longitude: -1.8936556,
            latitudeDelta: 0.0922,
            longitudeDelta: -1.8936556,
        },
        image: 'https://www.economiasolidaria.org/sites/default/files/styles/large/public/reaslibrary/images/125%20omal.PNG?itok=8rgqziyZ',
        description: 'Vídeo-resumen del curso internacional "Alternativas en Transición hacia una Economía Popular", que se encuentra en Gernika y Bilbao entre el 24 de septiembre y el 7 de marzo de 2018, con la participación de más de 20 activistas de América Latina, el sur de Europa y Euskal Herria.\n\nEl objetivo del curso era generar un espacio de formación e intercambio de experiencias de economía alternativa, autogestión y organización popular, además de conocer las   iniciativas de economía popular llevadas a cabo en Euskal Herria, como las impulsadas en los municipios de Urduña y Hernani, o los Proyectos de autogestión en Errekaleor (Gasteiz) y Astra (Gernika).\nMás información en:\nhttps://www.economiasolidaria.org/reas-euskadi/biblioteca/curso-internacional-alternativas-en-transicion-hacia-una-economia-popular.',
        info:'https://www.economiasolidaria.org/reas-euskadi/biblioteca/curso-internacional-alternativas-en-transicion-hacia-una-economia-popular',

    },
    {
        name: 'VI EKONOMIA FEMINISTAREN KONGRESUA 2019',
        data: '2019/11/17',
        type: 'enterprise-event',
        enterprise: 'Reas',
        enterpriseType: 'tecnology',
        eventDate: '2019-11-17',
        eventInitHour: '12:00',
        eventFinishHour: '13:00',
        like: 144,
        menbers: 34,
        direction: 'Balentzia',
        region: {
            latitude: 43.3220449,
            longitude: -1.9001347,
            latitudeDelta: 0.0922,
            longitudeDelta: -1.8936556,
        },
        image: 'https://femeconomiafeminista.com/wp-content/uploads/2019/04/POST-FACEBOOK-Congres-VAL.jpg',
        description: 'Irailak 5, 6 eta 7 egunetan Ekonomia Feminista Kongresuaren edizio berria ospatuko da Valentzian, REAS antolaketaren partaide aktibo izan delarik.\n\nEdizio berri honek aurreko urteetan sortutako esperientzia  zein ezagutzak kontuan ditu, baita ordutik elikatzen joan garen sare trukeak eta akzio politikoa ere.\n\nOraingo honetan, ekonomia feministarentzat garrantzi handiena duten gaiak landuko ditugu dinamika teoriko-praktikoen bitartez; politika publikoen bidez aplikagarriak diren tresnak (generoaren ikuspegia kontuan duten zerga eta aurrekontuak), gobernu eredu feministen definizioa, komunen kudeaketa eta erresistentzia feministen artikulazioa beligerentzia neoliberalaren aurrean.',
        info:'https://femeconomiafeminista.com/congres2019/'

    },
    {
        name: 'Pasea y descubre las rutas de otra economía!',
        data: '2019/11/17',
        type: 'enterprise-event',
        enterprise: 'Reas',
        enterpriseType: 'tecnology',
        eventDate: '2019-6-21',
        eventInitHour: '10:00',
        eventFinishHour: '13:30',
        like: 144,
        menbers: 34,
        direction: 'San nikolas eliza - Bilbo',
        region: {
            latitude: 43.3220449,
            longitude: -1.9001347,
            latitudeDelta: 0.0922,
            longitudeDelta: -1.8936556,
        },
        image: 'https://www.economiasolidaria.org/sites/default/files/inline-images/Ekonomia%20Eraldatuz%20ekaina.jpg',
        description: 'Desde REAS Euskadi nos hemos animado a organizar una actividad donde tendréis la oportunidad de conocer varias de las realidades de economía solidaria que conforman la red.\n\nSaliendo de la Iglesia de San Nicolás a las 9.15h del 21 de junio, haremos el primer alto en el camino en Ortuella, donde visitaremos la entidad Berziklatu, empresa de inserción de tratamiento de residuos voluminosos. De allí, volveremos a Bilbao, donde en la tienda de Labore Bilbo (el primer supermercado cooperativo de la ciudad) conoceremos el trabajo que hacen tanto Labore como Fiare Banca Etica y Goiener, y terminaremos la mañana con una degustación de productos de Labore. Durante el pikateko, podremos aprovechar para preguntar las dudas que se nos hayan quedado en el tintero a las compañeras de Fiare, Goiener y Labore.',
        info:'https://www.economiasolidaria.org/reas-euskadi/eventos/pasea-y-descubre-las-rutas-de-otra-economia '

    },
    {
        name: '¡Apoya nuestro crowdfunding #NecesitoRopaLimpia!',
        data: '2019/11/17',
        type: 'help',
        enterprise: 'Reas',
        enterpriseType: 'tecnology',
        eventDate: '2019-6-21',
        eventInitHour: '10:00',
        eventFinishHour: '13:30',
        direction: 'San nikolas eliza - Bilbo',
        region: {
            latitude: 43.3220449,
            longitude: -1.9001347,
            latitudeDelta: 0.0922,
            longitudeDelta: -1.8936556,
        },
        image: 'https://www.economiasolidaria.org/sites/default/files/styles/large/public/news/images/124%20ropa%20limpia.PNG?itok=1xVt7CRD',
        description:'La continuidad de Campaña Ropa Limpia y su labor para eliminar las condiciones de esclavitud de la industria textil está en riesgo y necesita tu apoyo. Por eso, te queremos pedir que apoyes esta campaña de crowdfunding que acabamos de sacar a la luz, con el hashtag #NecesitoRopaLimpia.\n\nEste crowdfunding busca recaudar fondos que permitan mantener nuestra labor en favor de unas condiciones laborales dignas en la industria textil y de calzado. Lanzada a través de la plataforma goteo.org, la campaña pretende recaudar un mínimo de 12.000€ en un plazo de 40 días.\n\nEl inicio está siendo ilusionante, con 60 personas que han colaborado y más de 3000 euros recaudados en dos días.\n\nSin embargo, queremos pedirte que nos ayudes difundiendo y/o aportando en https://goteo.cc/necesitoropalimpia para poder llegar al mínimo cuanto antes.\n\n¡Cualquier aportación será más que bienvenida! ¡Muchas gracias!',
        info:'https://www.economiasolidaria.org/reas-euskadi/noticias/apoya-nuestro-crowdfunding-necesitoropalimpia'

    },
]
